CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID),
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS (SUPPLIERS_ID),
CATEGORY_ID NUMBER,
CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID),
QUANTITY_PER_UNIT NUMBER,
UNIT_PRICE NUMBER(*,2),
UNITS_IN_STOK NUMBER,
UNITS_ON_ORDER NUMBER,
REORDER_LEVEL NVARCHAR2(20),
DISCONTINUED NUMBER
);