CREATE TABLE ORDER_DETAILS(
ORDER_ID NUMBER,
CONSTRAINT ORDERS_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCTS_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
UNIT_PRICE NUMBER(*,2),
QUANTITY NUMBER,
DISCOUNT NUMBER
);