CREATE TABLE ORDERS(
ORDER_ID NUMBER,
CONSTRAINT ORDERS_PK PRIMARY KEY (ORDER_ID),
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMERS_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEES_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
ORDER_DATE TIMESTAMP,
REQUIRED_DATE TIMESTAMP,
SHIPPED_DATE TIMESTAMP,
SHIP_VIA NVARCHAR2(20),
FREIGHT NVARCHAR2(10),
SHIP_NAME NVARCHAR2(30),
SHIP_ADDRESS NVARCHAR2(200),
SHIP_CITY NVARCHAR2(20),
SHIP_REGION NUMBER,
SHIP_POSTAL_CODE NUMBER,
SHIP_COUNTRY NVARCHAR2(20)
);