CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
ID NUMBER,
CONSTRAINT VOTES_PK PRIMARY KEY(ID),
ID_POLL_OPTION NUMBER,
CONSTRAINT FORUM_POLLS_OPTIONS_FK FOREIGN KEY(ID_POLL_OPTION)REFERENCES FORUM_POLLS_OPTIONS(ID),
ID_USER NUMBER,
CONSTRAINT USERS_VOTES_FK FOREIGN KEY(ID_USER) REFERENCES USERS_(ID),
DATE_ TIMESTAMP,
IP NVARCHAR2(20)
);