CREATE TABLE FORUM_POSTS(
ID NUMBER,
CONSTRAINT FORUM_POSTS_PK PRIMARY KEY(ID),
ID_SUBCATEGORY NUMBER,
CONSTRAINT FORUM_SUBCATEGORIES_FK FOREIGN KEY(ID_SUBCATEGORY)REFERENCES FORUM_SUBCATEGORIES(ID),
ID_USER NUMBER,
CONSTRAINT USERS_FK FOREIGN KEY(ID_USER)REFERENCES USERS_(ID),
PARENT_POST NUMBER,
CONSTRAINT FORUM_POSTS_FK FOREIGN KEY(PARENT_POST)REFERENCES FORUM_POSTS(ID),
TITLE NVARCHAR2(90),
CONTENT CLOB,
IS_POLL CHAR(1) CHECK (IS_POLL = 'Y' OR IS_POLL = 'N'),
DATE_ TIMESTAMP,
IP NVARCHAR2(20)
);