CREATE TABLE FORUM_SUBCATEGORIES(
ID NUMBER,
CONSTRAINT FORUM_SUBCATEGORIES_PK PRIMARY KEY(ID),
ID_CATEGORY NUMBER,
CONSTRAINT FORUM_CATEGORIES_FK FOREIGN KEY(ID_CATEGORY) REFERENCES FORUM_CATEGORIES(ID),
TITLE NVARCHAR2(45),
DESCRIPTION CLOB,
DATE_ TIMESTAMP,
IP NVARCHAR2(20)
);