CREATE TABLE CUSTOMERS(
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMERS_PK PRIMARY KEY (CUSTOMER_ID),
COMPANY_NAME NVARCHAR2(50),
CONTACT_NAME NVARCHAR2(30),
CONTACT_TITLE NVARCHAR2(20),
ADDRESS NVARCHAR2(100),
CITY NVARCHAR2(20),
REGION NUMBER,
POSTAL_CODE NUMBER,
COUNTRY NVARCHAR2(20),
PHONE NVARCHAR2(20),
FAX NVARCHAR2(20)
);