CREATE TABLE MOVIE(
  ID NUMBER,
  CONSTRAINT MOVIE_PK PRIMARY KEY(ID),
  TITLE NVARCHAR2(50) UNIQUE NOT NULL,
  DIRECTOR NVARCHAR2(50) NOT NULL,
  YEAR NUMBER(4) CHECK (YEAR >= 1900 AND YEAR <= 2018),
  LENGTH_MIN NUMBER CHECK (LENGTH_MIN >= 10 AND LENGTH_MIN <= 200)
);