INSERT INTO MOVIE_STAT
VALUES(1111, 6.13, 100, 150);

INSERT INTO MOVIE_STAT
VALUES(2222, 3.6, 40, 65);

INSERT INTO MOVIE_STAT
VALUES(3333, 4.9, 55, 90);

INSERT INTO MOVIE_STAT
VALUES(4444, 7.5, 150, 310);

INSERT INTO MOVIE_STAT
VALUES(5555, 4.8, 50, 80);

--SELECT SUM(DOMESTIC_SALES), SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT
--WHERE EXISTS (SELECT DIRECTOR FROM MOVIE WHERE MOVIE.ID = MOVIE_STAT.MOVIE_ID AND MOVIE.DIRECTOR = 'Director02');

--SELECT SUM(DOMESTIC_SALES), SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT
--WHERE EXISTS (SELECT DIRECTOR FROM MOVIE WHERE MOVIE.ID = MOVIE_STAT.MOVIE_ID AND MOVIE.DIRECTOR = 'Director01');

SELECT MOVIE.DIRECTOR, SUM(DOMESTIC_SALES), SUM(INTERNATIONAL_SALES) FROM MOVIE_STAT, MOVIE
WHERE MOVIE.ID = MOVIE_STAT.MOVIE_ID
GROUP BY MOVIE.DIRECTOR;